// import { Button } from 'bootstrap'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import router from 'next/router'


export default function Login() {

    const masuk = () => {
        localStorage.setItem('token', 'usertoken')
        router.push('/home')
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Login Page</div>

      <button onClick={() => masuk()}>login</button>
    </div>
  )
}
