import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import { useSession } from 'next-auth/client'
import { useState, useEffect } from 'react'

export default function Home() {
  const [ session, loading ] = useSession()
  const [ content , setContent ] = useState()
  useEffect(()=>{
    const fetchData = async () => {
      const res = await fetch('/api/examples/protected')
      const json = await res.json()
      console.log(json)
      if (json.content) { setContent(json.content) }
    }
    fetchData()
  },[session])

  if (!session) { return  <Layout><div>Test</div></Layout> }
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Landing Page, {session}</div>
    </div>
    </Layout>
  )
}
