import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import router from 'next/router'

export default function HomeDashboard() {
    const keluar = () => {
        localStorage.removeItem('token')
        router.push('/auth/login')
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Setelah Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Dashboard Home Setelah Login</div>
      <button onClick={() => keluar()}>logout</button>
    </div>
  )
}
